pdf:
	pandoc \
		./index.md \
		./_tutorial/index.md \
		./_tutorial/01-getting-started.md \
		./_tutorial/02-first-process.md \
		./_explain/index.md \
		./_explain/01-validity-truthiness.md \
		./_explain/02-composition.md \
		./_explain/03-processes.md \
		./_reference/index.md \
		./_reference/01-types.md \
		./_reference/02-functions.md \
		./_reference/03-structures.md \
		-o output.pdf \
		-V geometry:margin=1in \
		-V author="" \
		-V date="" \
		-V title=""
